// Builds the derived files from src/engine.js and src/element.mjs:
//   src/engine.mjs          ES module version of the engine
//   dist/pixel-anirudh.js   one classic <script> file: engine + <pixel-anirudh> element
// Run: npm run build
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const engine = readFileSync(join(root, 'src/engine.js'), 'utf8');
const element = readFileSync(join(root, 'src/element.mjs'), 'utf8');

const cut = engine.indexOf("if (typeof module !== 'undefined'");
if (cut < 0) throw new Error('engine.js: CommonJS export line not found');
const core = engine.slice(0, cut).replace('var PixelAnirudh = (function(){', 'const PixelAnirudh = (function(){');

writeFileSync(join(root, 'src/engine.mjs'), core + 'export default PixelAnirudh;\nexport { PixelAnirudh };\n');

const el = element
  .replace(/^import PixelAnirudh from '\.\/engine\.mjs';\n/m, '')
  .replace(/^export class /m, 'class ')
  .replace(/^export default PixelAnirudhElement;\n?/m, '');
mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist/pixel-anirudh.js'),
  '/* pixel-anirudh bundle: engine + <pixel-anirudh> element. Generated by scripts/build.mjs, do not edit. */\n' +
  '(function(){\n' + core + '\n' + el + '\nwindow.PixelAnirudh = PixelAnirudh;\nwindow.PixelAnirudhElement = PixelAnirudhElement;\n})();\n');
console.log('built src/engine.mjs and dist/pixel-anirudh.js');
